name: sn17-gen-v1

channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.11
  - pytorch::pytorch=2.4.0
  - pytorch::torchvision=0.19.0
  - pytorch::torchaudio=2.4.0
  - pytorch::pytorch-cuda=12.4
  - pip
  - ffmpeg
  - git
  - pip:
      - xformers==0.0.27.post2
      - diffusers==
      - transformers
      - sentencepiece
      - accelerate>=0.33.0
      - safetensors>=0.4.3
      - open-clip-torch>=2.24.0
      - einops
      - opencv-python-headless
      - imageio
      - lpips
      - scikit-image
      - fastapi
      - uvicorn[standard]
      - loguru
      - trimesh
      - pygltflib
      - simple-aesthetics-predictor
      - httpx
      - python-multipart
      - python-dotenv
      - hf_transfer
      - kornia
