name: sn17-miner-v1
channels: [pytorch, nvidia, conda-forge]
dependencies:
  - python=3.11
  - pytorch::pytorch=2.4.1
  - pytorch::torchvision=0.19.1
  - pytorch::torchaudio=2.4.1
  - pytorch::pytorch-cuda=12.4
  - pip
  - git
  - ffmpeg
  - pip:
      - diffusers>=0.30.0
      - transformers>=4.43
      - open-clip-torch>=2.24.0
      - accelerate>=0.33.0
      - xformers>=0.0.27
      - einops
      - opencv-python-headless
      - imageio
      - lpips
      - scikit-image
      - fastapi
      - uvicorn[standard]
      - loguru
      - trimesh
      - pygltflib
      - simple-aesthetics-predictor
      - httpx
      - python-multipart
