name: sn17-miner-v1
channels: [conda-forge]
channel_priority: strict
dependencies:
  - python=3.11
  - git
  - ffmpeg
  - pip
  - pip:
      - torch==2.4.1+cu124
      - torchvision==0.19.1+cu124
      - torchaudio==2.4.1+cu124
      - --extra-index-url https://download.pytorch.org/whl/cu124
      - diffusers>=0.30.0
      - transformers>=4.43
      - open-clip-torch>=2.24.0
      - accelerate>=0.33.0
      - xformers>=0.0.27
      - einops
      - opencv-python-headless
      - imageio
      - lpips
      - scikit-image
      - fastapi
      - uvicorn[standard]
      - loguru
      - trimesh
      - pygltflib
      - simple-aesthetics-predictor
      - httpx
      - python-multipart
